### ISSUE TITLE
leave action blank unless referencing a different file

### ISSUE THREAD

**Issue by billythakidd04** [williamrockowl/webdevcourse#2]
https://github.com/williamrockowl/webdevcourse/blob/3242ea68f62f540df5c01be827197f0fd7be1012/madlibs.php#L6

unless the form is being processed by a totally different file, dont include it or set it to ""

**Comment by williamrockowl** [comment]
made action ""

**Comment by billythakidd04** [comment]
> made action ""

where? what commit/pr?
