### ISSUE TITLE
submit has no name attribute

### ISSUE THREAD

**Issue by billythakidd04** [williamrockowl/webdevcourse#4]
https://github.com/williamrockowl/webdevcourse/blob/3242ea68f62f540df5c01be827197f0fd7be1012/madlibs.php#L11

if you plan to reference the submit button via php, the easiest way is to make sure you set a name attribute.

**Comment by williamrockowl** [comment]
made name="submit_btn"

**Comment by billythakidd04** [comment]
commit/pr?
